-- Member 테이블 관리를 위한 ddl.sql 파일 생성해서 사용한다.
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    password varchar(255),
    email varchar(255),
    point varchar(255)
    primary key (id)

);